// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestLoom.Api.Data;

#nullable disable

namespace RequestLoom.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808211325_AddRequestVariableEnabled")]
    partial class AddRequestVariableEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ApiRequestRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body_type");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_favorite");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PostRequestScript")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("post_request_script");

                    b.Property<string>("PreRequestScript")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pre_request_script");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("TestScript")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_script");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("requests");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.EnvironmentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("environments");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.EnvironmentVariableRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("environment_id");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("environment_variables");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.HistoryRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ExecutedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("executed_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_body");

                    b.Property<string>("RequestHeadersJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_headers_json");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("response_body");

                    b.Property<string>("ResponseHeadersJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("response_headers_json");

                    b.Property<long>("ResponseSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_size_bytes");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_status");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_time_ms");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("RequestId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("history");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.MockServerEndpointRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DelayMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delay_ms");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<string>("MockServerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mock_server_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("response_body");

                    b.Property<string>("ResponseHeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("response_headers_json");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("script");

                    b.Property<bool>("ScriptEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("script_enabled");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("MockServerId");

                    b.ToTable("mock_server_endpoints");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.MockServerRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_running");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("mock_servers");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestAuthRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_type");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("config_json");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("request_auth");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestHeaderRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("request_headers");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestParamRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("request_params");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestSettingsRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("FollowRedirects")
                        .HasColumnType("INTEGER")
                        .HasColumnName("follow_redirects");

                    b.Property<bool>("IgnoreSslErrors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ignore_ssl_errors");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_seconds");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("request_settings");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestVariableRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("request_variables");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ServiceAuthRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_type");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("config_json");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("service_auth");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ServiceHeaderRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("service_headers");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ServiceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("services");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ServiceVariableRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EnvironmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("environment_id");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("service_variables");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.WorkspaceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("workspaces");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.WorkspaceVariableRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EnvironmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("environment_id");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("workspace_variables");
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ApiRequestRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ServiceRow", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.EnvironmentRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.EnvironmentVariableRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.EnvironmentRow", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.HistoryRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ApiRequestRow", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RequestLoom.Api.Data.Entities.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.MockServerEndpointRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.MockServerRow", null)
                        .WithMany()
                        .HasForeignKey("MockServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.MockServerRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestAuthRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ApiRequestRow", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestHeaderRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ApiRequestRow", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestParamRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ApiRequestRow", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestSettingsRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ApiRequestRow", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.RequestVariableRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ApiRequestRow", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ServiceAuthRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ServiceRow", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ServiceHeaderRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ServiceRow", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ServiceRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.ServiceVariableRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.ServiceRow", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestLoom.Api.Data.Entities.WorkspaceVariableRow", b =>
                {
                    b.HasOne("RequestLoom.Api.Data.Entities.EnvironmentRow", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RequestLoom.Api.Data.Entities.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
